# Generated by Django 2.0.3 on 2018-04-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20180402_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todoTitle',
            new_name='title',
        ),
    ]
