# Generated by Django 2.0.3 on 2018-04-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20180403_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
    ]
